### ISSUE TITLE
Opennic uses HTTPS now

### ISSUE THREAD

**Issue by DoctorJellyface** [mar77i/opennic#1]
The warnings in the README file should now be obselete.

**Comment by mar77i** [comment]
Now that's in the README.md, I'm honestly undecided whether to just take it out. Can you support your argument with the necessary facts?

**Comment by mar77i** [comment]
Just noticed the script actually does use HTTPS. I guess this resolves the issue.

**Comment by mar77i** [comment]
resolved with #0b1f4f0a727a38bee0a0d155b4d71da7274d6e9d
