### ISSUE TITLE
similar project

### ISSUE THREAD

**Issue by kewlfft** [mar77i/opennic#4]
fyi
I have developed a similar project [here](https://github.com/kewlfft/opennic-up), happy to exchange or join efforts.

**Comment by mar77i** [comment]
That's no problem to me, I guess. I don't and probably will at no point intend to
- rely on google's 8.8.8.8 dns server
- or depend on NetworkManager, fping or ldns/drill

**Comment by kewlfft** [comment]
thanks for your feedback, it gives me some developement ideas: I can replace google by another server, this is probably a good idea.
opennic turns out to be very bad at returning good servers around me, it must not be mapping my ip to the right country. I need to do the testing myself and fping is pretty good at pinging in parallel many of them but I am open to alternative approaches.

**Comment by kewlfft** [comment]
I could replace 8.8.8.8 by 185.121.177.177 it makes more sense

**Comment by mar77i** [comment]
Why not use the first one that works from the list returned from opennic?

**Comment by kewlfft** [comment]
I have updated and don't use Google any longer, thanks for the feedback.
The first working one returned from opennic is relatively slow, after sorting I can get one 10ms away.
