### ISSUE TITLE
GeoIP returning wrong location

### ISSUE THREAD

**Issue by kewlfft** [mar77i/opennic#5]
As reported [here](https://wiki.opennic.org/api/geoip#known_issues) the GeoIP API is known to report servers in an inaccurate or wrong location.
This is happening with my IP and I am getting servers very far from my location.
An alternative could be to indicate lat & lon maybe?

**Comment by mar77i** [comment]
I was not aware about GeoIP issues being this serious.

**Comment by kewlfft** [comment]
I am not getting better results with lan & lon then I am not sure why the API is not returning results in my country first.

**Comment by mar77i** [comment]
@kewlfft did you find a solution to this problem that I could offer in the configuration?

And to pose the question more specifically, do your own country's opennic servers give you a faster DNS experience compared to those offered through GeoIP?

**Comment by kewlfft** [comment]
yes definitely 10ms response time vs about 100ms for the one returned by the GeoIP request

**Comment by kewlfft** [comment]
I agree it is not really the best approach, this just a workaround it would be better to report it upstream and improve the geoip function used or do some sorting at the server level rather than at my level.

**Comment by mar77i** [comment]
At the current time, this just seems out of the scope of this project.
Here is a quick way to retrieve a list of tier 2 servers:
```bash
opennic_ips() {
    local a="[0-9]{1,3}" b=RSTART c=RLENGTH
    local ipv4_xpath="//span[contains(@class, 'ipv4')]/parent::node()"
    curl -sL https://servers.opennicproject.org/| \
      xmllint --html --recover --xpath "$ipv4_xpath" - 2>/dev/null| \
      awk "{while(match(\$0, /$a\.$a\.$a\.$a/)){print substr(\$0,$b,$c);\$0=substr(\$0,$b+$c);}}"
}
```

**Comment by kewlfft** [comment]
Not bad at all, what about filtering a particular country out of the list. I am going to have a look.
