### ISSUE TITLE
systemd service interferes with remote filesystem mounting during boot

### ISSUE THREAD

**Issue by ohnonot** [mar77i/opennic#6]
Uing this on ArchLinux, I have 2 NFS mounts in /etc/fstab. Those get picked up by systemd automatically, however since enabling this opennic systemd service, the mount would always fail.

I know that api.opennicproject.org is sometimes slow to respond, and when I think about it, the process of rewriting resolv.conf does not really belong in the boot process:

- the user must already have some means of DNS resolution _before_ switching to opennic servers
- _after_ the switch to opennic, it is not mandatory to change servers too often; all nameresolving softwares have solutions to switch to another server if one is out, and anyhow, the servers don't usually just die, opennic just shifts them around according to responsiveness etc.

I think it makes much more sense to have e.g. a daily timer. I have now [forked this repo and added 2 more systemd files](https://github.com/ohnonot/opennic). This has been working for me for about a week now (i see that resolv.conf gets updated).

Do you want a pull request straight away?  
Of course the choice is yours, I'm just not sure about etiquette in these situations.

**Comment by mar77i** [comment]
Please let me decide on this feature in a pull request. Thanks for the notification, my initial reaction is that you might have a point there.

On the other hand, nowhere does the service file as I provide it say you should enable it as a boot service. But that might be my own RTFM lazy approach at `systemd`.

**Comment by ohnonot** [comment]
> Please let me decide on this feature in a pull request.

Sorry, I don't understand. Does this mean you want me to make a pull request?

> nowhere does the service file as I provide it say you should enable it as a boot service.

well you _should_ enable it to use it, and it requires `network.target`, which is normally reached during boot, even before `multi-user.target`.

**Comment by mar77i** [comment]
> Sorry, I don't understand. Does this mean you want me to make a pull request?

Yes it does.

> well you should enable it to use it, and it requires network.target, which is normally reached during boot, even before multi-user.target.

Well this might be me being illiterate with systemd again, because I added network.target as a requirement since the package is pointless without a network connection. 

FWIW, `systemctl | grep opennic` is empty on my laptop.

**Comment by ohnonot** [comment]
Maybe there's a misunderstanding here.  
Usually, network initialization is part of the system initialization (i.e. booting).  
If you say laptop, maybe you are thinking in terms of booting offline, and creating a Wifi connection later. On my machine, the connection is wired and intialized during boot. I'm not completely sure, but I think `network.target` is always reached during boot (on an ootb systemd configuration), even if you're not connected to a network.

Anyhow, here's the pull request. I'm sure both approaches can be included in the repo.
I also added a stanza to the README.

Before closing, I will conduct a few more tests with both approaches, maybe I can eliminate some maybes then.

**Comment by mar77i** [comment]
> If you say laptop, maybe you are thinking in terms of booting offline, and creating a Wifi connection later. On my machine, the connection is wired and intialized during boot. I'm not completely sure, but I think network.target is always reached during boot (on an ootb systemd configuration), even if you're not connected to a network.

I don't think I want the `opennic` script to run on every boot. That would be silly.

How about we consider these timers and service files not part of this project and we remove them from the repository entirely?

**Comment by ohnonot** [comment]
> I don't think I want the opennic script to run on every boot. That would be silly.

so maybe a weekly timer would be appropriate?

> How about we consider these timers and service files not part of this project and remove them from the repository entirely?

the system integration is the reason why i installed it from the AUR; i would not remove this.

btw, i reverteded back to the old (your) systemd service and cannot reproduce the original problem anymore! i'm flummoxed.  
but surely it's not wrong to leave my additions in here. If you want to change the timer to weekly, simply change `OnCalendar...` to `OnCalendar=weekly` (that would execute each monday at 12am).

**Comment by ohnonot** [comment]
I wasn't able to reproduce the original problem, but I noticed something else today: the journal was flooded with messages like this: "using degraded feature set (TCP/UDP) for dns server xx.xx.xx.xx". The IPs were NOT the same as in /etc/resolv.conf.

It was enough to restart the service: `systemctl restart systemd-resolved` to make those messages go away.

What happened?  
I _think_ that for some reason the opennic script in this repo wasn't quite done yet doing its thing.  
Whatever the reason, `systemd-resolved` reverted back to a list of (outdated) fallback servers.  
IMO, just one more reason to move nameserver updating away from the boot procedure.

**Comment by mar77i** [comment]
Yes, you should have `systemd-resolved` deactivated so that your resolv.conf is actually let to do the work. Another one of those systemd-related uncertainities...

**Comment by ohnonot** [comment]
No. systemd-resolved is well able to deal with something else updating `/etc/resolv.conf`. From its man page:

>Alternatively, /etc/resolv.conf may be managed by other packages, in which case
           systemd-resolved will read it for DNS configuration data. In this mode of operation
           systemd-resolved is consumer rather than provider of this configuration file.  
Note that the selected mode of operation for this file is detected fully automatically,
       depending on whether /etc/resolv.conf is a symlink

No, the problem is that opennic's api sometimes (not often) takes a while to respond (i know this from other experiences), and that seems to mess up the systemd init process.

I'll say it again, querying a sometimes-stressed web api is fragile and should not be part of early boot.  
It doesn't make much sense anyway in this case because the servers don't shift around that often (and even if, all dns resolvers already have a mechanism built in for dealing with failing nameservers).

I'm booting my machine once or twice a day, and that's the speed at which I'll continue troubleshooting this, but I'm on it.

**Comment by mar77i** [comment]
> I'll say it again, querying a sometimes-stressed web api is fragile and should not be part of early boot.
It doesn't make much sense anyway in this case because the servers don't shift around that often (and even if, all dns resolvers already have a mechanism built in for dealing with failing nameservers).

I never disputed that. On the contrary:
> FWIW, systemctl | grep opennic is empty on my laptop.

What I tried to say here is that I don't have the service enabled for boot. The service file I included is indeed ill-advised and probably wrong. Do you want me to remove it?

Please do not run this script every boot.
